Objetivo 1 - Estructura general y planificación del proyecto
moshidev/MaquiTracker pull request #4
Opened 2023-09-20 16:24 UTC by moshidev

Sobre los milestones:

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Sobre las historias de usuario:

* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-21 18:27 UTC, moshidev commented
@JJ ¿Podrías echarle un vistazo a las historias de usuario que he subido? He intentado seguir los pasos que se describen en el libro User Stories Applied, de Mike Cohn, y creo que está bien, pero hay algo que me dice que estoy haciendo las historias sistemáticamente mal... Te agradecería mucho un poco de feedback antes de continuar.

2023-09-21 18:39 UTC, JJ requested changes
En general, preferiría que lo enviárais antes de corregirlo. No pasa nada porque lo tengáis que enviar otra vez.

En el caso que expones, yo dejaría la mayoría de las HUs como simples issues; el problema es que ese tipo de issues corresponden a una modelización del problema que habrás visto seguramente que corresponde al objetivo 2, y que hará otra persona.

2023-09-21 18:39 UTC, JJ commented on docs/historias_usuario.md
> +## [HU001] El propietario puede recuperar un histórico de incidentes.
En general, el concepto de historia de usuario que aparece en la literatura es un poco más amplio que el que usamos en la asignatura. En general, se propone las historias de usuario simplemente como un formato para expresar claramente los problemas que hay que resolver por parte del programador.

Lo que llamamos en IV historias de usuario es un poco más restringido, como hemos explicado hoy en clase. Tiene dos características básicas: tiene que expresar un deseo del usuario ("ojalá que...") y tiene que referirse a la lógica de negocio. En este caso específico, no cumple ninguno de los dos. Sería un issue válido, porque para cumplir los deseos es posible que quiera recuperar un histórico de incidentes, o sea una característica que tú quieres que esté en tu producto. Pero nosotros tenemos una visión mucho más restringida, sobre todo mirando a que sólo podemos crear un poco de código (el relativo a la lógica de negocio) y no el producto completo.

También la secuenciación de las HUs es más o menos importante. El primer problema que habría que resolver, ¿sería un histórico del funcionamiento?

2023-09-21 18:49 UTC, moshidev commented on docs/historias_usuario.md
> +## [HU001] El propietario puede recuperar un histórico de incidentes.
Bien, hay algunas cosas que todavía no entiendo bien, las revisito y corrijo las historias de usuario.

Por otra parte la lógica que he seguido para los hitos ha sido el que el histórico es el fin de utilizar el producto, y que el que un usuario tenga máquinas o no es algo necesario pero no el fin en sí. Si es mejor empezar por otra parte puedo reorganizar los hitos.

2023-09-21 18:53 UTC, JJ commented on docs/historias_usuario.md
> +## [HU001] El propietario puede recuperar un histórico de incidentes.
Un histórico es simplemente almacenar y recuperar la información. Totalmente válido como planteamiento de producto, inválido para esta asignatura porque si no hay una lógica de negocio sustancial no se puede llevar a cabo el objetivo 4.
Yo entendí por el objetivo 0 que el verdadero problema eran las estadísticas. Si quieres incluir el histórico como historia de usuario en realidad no hay ningún inconveniente, pero quiero que seas consciente de que tendría que tener prioridad baja (tipo no lo voy a hacer en la asignatura, y por tanto un índice alto), porque las que tengan prioridad más alta (con las que realmente vayas a trabajar) tienen que tener las características que te comento.

2023-09-21 19:10 UTC, moshidev commented on docs/historias_usuario.md
> +## [HU001] El propietario puede recuperar un histórico de incidentes.
Entiendo, claro, queremos quitarle prioridad a aquellas historias con poca o ninguna lógica de negocio, como el caso del histórico, como requisito de la asignatura para los objetivos siguientes. Ahora entiendo mejor la razón de este objetivo y por qué se quieren formular las historias de usuario de esta forma. Voy a intentar mejorar estas cosas, esta vez haciendo un pullreq en IV-.

2023-09-25 12:35 UTC, JJ reviewed
Recuerda que en principio las historias de usuario deben contener todo lo necesario (y sólo lo necesario) para crear un modelo del problema.

2023-09-25 12:35 UTC, JJ commented on docs/historias_usuario.md
> +Como propietario de la máquina quiero que, dado una máquina con sensores y capacidad de conectarse a Internet,
Como comenté en el objetivo 0, todo lo que tenga cualquier tipo de input físico es muy difícil de tratar. Me vale sin embargo en el sentido que supongo que tienes esos datos en algún lugar y que no vas a necesitar, durante la asignatura, conectarte a dicha máquina para ver lo que sale.

2023-09-25 12:35 UTC, JJ commented on docs/historias_usuario.md
> +de uso pasado y las lecturas de sus sensores. En el peor de los casos, me gustaría conocer si una máquina está
Son dos problemas diferentes, deberías dividirlo en sendas historias de usuario.

2023-09-25 12:35 UTC, JJ commented on docs/hitos.md
> +Asociado a [HU001](historias_usuario.md#hu001-mantenimiento-preventivo)
Las asociaciones de HU a milestones siempre son temporales, y sobre todo para que lo pongas en GitHub

2023-09-25 12:35 UTC, JJ commented on docs/hitos.md
> +- [ ] Para cada componente, si procede, conocemos los síntomas de que vaya a fallar.
Es demasiado detalle para un milestone. Todo  el contexto que sea necesario para modelizar el problema debe de estar en la HU.

2023-09-25 12:35 UTC, JJ commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
Todos los hitos deben de describirse como un producto.

2023-09-25 17:37 UTC, moshidev commented on docs/historias_usuario.md
> +Como propietario de la máquina quiero que, dado una máquina con sensores y capacidad de conectarse a Internet,
Sí, justamente, la idea para la asignatura es centrarse en la parte de análisis. Dado unos datos, el servicio devuelve un diagnóstico.

Tengo datos para hacer pruebas, no es necesario conexión con una máquina o interacción con usuarios.

2023-09-25 18:19 UTC, moshidev commented
@MarioGuisado @Morad02 Creo que ya está! Aunque dos cabezas piensan mejor que una. ¿Cómo lo veis?

2023-09-25 18:50 UTC, MarioGuisado commented
Estas describiendo en qué momento el hito es alcanzado, es decir, el criterio que se sigue para validarlo, pero falta describir cual es el producto que se va a entregar en cada uno, es decir, lo que entregaría la persona a la que se le asigna el hito (un fichero con datos normalizados, un algoritmo implementado, la corrección de unas funciones concretas etc). Además, el hito 0 debe ser la base por la que empezaría el desarrollo del proyecto (identificar el problema y crear las estructuras necesarias en código para tratarlo), lo que está describiendo ahora mismo ese hito es la funcionalidad final que se quiere conseguir.

2023-09-25 19:17 UTC, moshidev commented
Entiendo, subo las correcciones. Mi planteamiento original ha sido:

Hito 0 -> Descubrimos qué hace que una máquina falle y cómo lo detectamos, y elegimos un algoritmo para la parte de mantenimiento preventivos. Lo documentamos.

(La cosa es que todavía estamos investigando cómo detectarlo junto al cliente, sin tener este hito no creo que tenga sentido codificar nada, no sabemos la variabilidad/fiabilidad de los sensores, qué tipos de sensores hay, etc. Entiendo que la entrega del Objetivo-2 la seguimos haciendo nosotros y no otra persona, por lo que no habría problema?)

Hito 1 -> Modelizamos, a partir de la investigación del Hito 0, el problema mediante código.

2023-09-26 05:20 UTC, JJ commented
> Entiendo, subo las correcciones. Por si todavía hay cosas mejorables que no pueda identificar... La lógica que he seguido para plantearlo así ha sido la siguiente:
> 
> Hito 0 -> Descubrimos qué hace que una máquina falle y cómo lo detectamos, y elegimos un algoritmo para la parte de mantenimiento preventivos. Lo documentamos.
> 
> (La cosa es que todavía estamos investigando cómo detectarlo junto al cliente, sin tener este hito no creo que tenga sentido codificar nada, no sabemos la variabilidad/fiabilidad de los sensores, qué tipos de sensores hay, etc. Entiendo que la entrega del Objetivo-2 la seguimos haciendo nosotros y no otra persona, por lo que... ¿no habría problema?)
> 
> Hito 1 -> Modelizamos, a partir de la investigación del Hito 0, el problema mediante código.

No, la del objetivo 2 la hace otra persona, pero tú tienes que proporcionar los datos para hacer el modelo.

2023-09-26 05:23 UTC, moshidev commented
Bien, gracias por el feedback. Volveré a pedir revisión cuando tenga datos suficientes como para que alguien pueda hacer el modelo.

2023-09-29 08:08 UTC, carlosservi commented on docs/historias_usuario.md
> +
Se podría añadir un poco más de contexto, por ejemplo, Como propietario de la máquina, la tengo alquilada a una empresa de x, y necesito saber el estado de la máquina para saber si tengo que hacerle una revisión, etc... Creo que de esa forma se entiende un poco mejor lo que intenta expresar.

2023-09-29 10:12 UTC, moshidev commented on docs/historias_usuario.md
> +
He añadido más datos.

2023-09-29 10:15 UTC, moshidev commented
@MarioGuisado @Morad02 Listo para revisión.

2023-10-03 09:39 UTC, JJ commented
> @MarioGuisado @Morad02 Listo para revisión.

Por favor, @MarioGuisado @morad02 echadle un vistazo a esto y aprobadlo para que pueda pasar yo a revisarlo. En general, os rogaría que revisárais o aceptárais en menos de tres días desde la petición.

2023-10-05 07:31 UTC, carlosservi approved these changes

2023-10-05 08:09 UTC, moshidev commented
@JJ Listo para revisión.

2023-10-05 10:23 UTC, JJ requested changes
Creo que faltarían todavía algunos detalles para conseguir el objetivo de la formulación de las HUs de forma que se pueda trabajar con ellos en el siguiente objetivo pero, sobre todo, de aclarar para ti mismo cómo vas a validar los algoritmos que te digan si una máquina necesita reparación o no.

2023-10-05 10:23 UTC, JJ commented on docs/historias_usuario.md
> +degradado su funcionamiento. También me ayudaría bastante poder registrar y
¿"También" forma parte del mismo problema o es otra HU diferente? ¿Eso contribuye a saber si está funcionando de forma incorrecta? ¿No tiene otra forma de saber si antigüedad?

2023-10-05 10:23 UTC, JJ commented on docs/historias_usuario.md
> +
Recuerda resolver los comentarios indicando el commit donde se han resuelto (o cambiando la línea donde se han hecho, que los resuelve automáticamente)

2023-10-05 10:23 UTC, JJ commented on docs/historias_usuario.md
> +sensores. Tal vez podría ayudar poder registrar y consultar la antigüedad de
¿Tal vez? O ayuda o no ayuda. En todo caso, si es un elemento de juicio para saber el mantenimiento preventivo sería un dato que tendría que usar la lógica de negocio. Además, el propietario de la máquina sabrá su antigüedad, ¿no? Exprésalo como contexto, no como algo que "tenga que saber o quiera saber"

2023-10-05 10:23 UTC, JJ commented on docs/problema.md
> +* Quieren saber **cuánto** se ha utilizado la máquina, de forma que puedan realizar un **mantenimiento preventivo** eficiente.
Si es sólo consultar un dato almacenado, puede ser interesante (para un TFG por ejemplo), pero al no implicar ninguna lógica de negocio, no sería parte de esta asignatura.

2023-10-05 10:23 UTC, JJ commented on docs/problema.md
> +Los clientes que poseen más de una máquina o aquellos que alquilan a terceros quieren conocer el estado y uso de sus máquina de la forma más frecuente posible, sin estar presentes.
Recuerda que en el objetivo 0 lo que buscamos es la expresión de un problema. Todo lo que dices que se tiene que conocer será el contexto del problema, pero tal como lo has formulado en las HU sería conveniente que dijeras qué beneficio quieren obtener, la razón por la que quieren conocer todo eso.

2023-10-05 10:24 UTC, JJ commented
Quizás sería conveniente que le hicieran una ronda de revisión @shvtwp @pluque01 @josemponce, por ejemplo.

2023-10-05 10:36 UTC, moshidev commented on docs/historias_usuario.md
> +
Resuelto en [6449da5](https://github.com/moshidev/MaquiTracker/pull/4/commits/6449da5cf0603a01de1b53b289973b8efc74f801)

2023-10-05 10:37 UTC, moshidev commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
Resuelto en [a9660fd](https://github.com/moshidev/MaquiTracker/pull/4/commits/a9660fdba333345b819ba2e9a7ae8f64bd1e5fdd).

2023-10-05 10:38 UTC, moshidev commented on docs/hitos.md
> +- [ ] Para cada componente, si procede, conocemos los síntomas de que vaya a fallar.
Resuelto en [3bba464](https://github.com/moshidev/MaquiTracker/pull/4/commits/3bba4647f489abc7bc8ea0d6efbeba25c776060c).

2023-10-05 10:41 UTC, moshidev commented on docs/hitos.md
> +Asociado a [HU001](historias_usuario.md#hu001-mantenimiento-preventivo)
Resuelto en 966f2e1.

2023-10-05 10:43 UTC, moshidev commented on docs/historias_usuario.md
> +de uso pasado y las lecturas de sus sensores. En el peor de los casos, me gustaría conocer si una máquina está
Resuelto en 0b867fb.

2023-10-06 06:56 UTC, moshidev commented on docs/problema.md
> +Los clientes que poseen más de una máquina o aquellos que alquilan a terceros quieren conocer el estado y uso de sus máquina de la forma más frecuente posible, sin estar presentes.
Resuelto en dd73145.

2023-10-06 06:57 UTC, moshidev commented on docs/problema.md
> +* Quieren saber **cuánto** se ha utilizado la máquina, de forma que puedan realizar un **mantenimiento preventivo** eficiente.
Todavía queda por investigar si definitivamente el problema pertenece a la asignatura. En principio resuelto en dd73145.

2023-10-06 07:30 UTC, pluque01 commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
Aquí escribes Implementa la lógica de negocio, sin embargo, por el contenido no me queda claro cuál va a ser la lógica de negocio para el proyecto. Si no especificas una lógica de negocio para el hito 1 no vas a poder hacer el objetivo 4. Intenta explicar cual es la solución que le estás ofreciendo a tus usuarios.

2023-10-06 07:38 UTC, moshidev commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
En qué sentido, en especificar en el hito 1 las características a implementar? En plan, a referenciar lo que ya está descrito en las historias de usuario?

2023-10-06 07:43 UTC, JJ commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
Sólo si es excesivamente compleja para que quepa en un solo hito.

2023-10-06 07:59 UTC, moshidev commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
https://github.com/moshidev/MaquiTracker/commit/83dcd6dad821acfa465b392473f4e472d1bba0ee Se entiende mejor así?
Al menos en la descripción del hito, quedan por mejorar las HUs

2023-10-06 08:03 UTC, pluque01 commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
Se entiende mucho mejor :))

2023-10-06 08:06 UTC, moshidev commented on docs/hitos.md
> +# Hito 1 - Implementa la lógica de negocio
thx!

2023-10-10 08:30 UTC, moshidev commented on docs/historias_usuario.md
> +sensores. Tal vez podría ayudar poder registrar y consultar la antigüedad de
Resuelto en 61dc7bb. Queda pendiente aclarar cómo se van a validar los algoritmos, estoy trabajando en ello.

2023-10-10 08:32 UTC, moshidev commented
Todavía estoy corrigiendo algunas cosas y añadiendo otra información fundamental para entender el proyecto.

2023-10-10 16:50 UTC, moshidev commented
@JJ He intentado aclarar más la formulación del problema. Está listo para revisión.

2023-10-10 20:37 UTC, merged